# Learn more about filters
# https://api-platform.com/docs/core/filters
services:

    blog_post.group_filter:
        parent: 'api_platform.serializer.group_filter'
        arguments:
            - 'groups'
            - false
        tags: [ 'api_platform.filter' ]